### ISSUE TITLE
Incorporate FindBugs into maven build; track total number of FindBugs warnings per project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#427] opened 2015-03-16 23:02 UTC
```
Now that Ontopia is build using Maven, it is trivially easy to use the FindBugs 
plug-in to find bugs in code.

For example, I tried the following command line to analyze just the 
ontopia-engine project:

C:\Rogue\ThirdParty\ontopia\ontopia-engine>mvn clean package findbugs:findbugs 
findbugs:gui

The tool identified 526 bugs in that project ranging from benign problems such 
as redundant assignments, dead code, unused fields, etc. to not-so-benign 
problems such as null pointer dereferencing, resource leaks, performance 
bottlenecks, etc.
```

Original issue reported on code.google.com by `faseidl2...@gmail.com` on 8 Nov 2011 at 8:56

**Comment by qsiebers** [comment] 2017-04-11 15:35
Duplicate of #45

**Closed by qsiebers** 2017-04-11 15:35 UTC
Labels: Enhancement, GoogleCode, Management-Maven, Newbie, Priority-Low
