### ISSUE TITLE
Transaction is not active exception in ontopoly after modifying a topic in a listener

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ontopia/ontopia#247] opened 2015-03-16 22:57 UTC
```
1. User creates a new topic in ontopoly
2. Ontopoly shows pop up dialog with the new topic
3. TopicMapListener triggers
4. TopicMapListener creates a new thread, B
5. B creates a new transaction
6. B modifies topic
7. B commits and closes transaction
8. User enters a new occurrence value
9. Ontopoly displays "Do you want to navigate away from the current page"
in firefox
10. Ontopoly displays exception stack trace

2010-05-25 10:30:30,872  [ERROR] (org.apache.wicket.RequestCycle:1521) 
Exception in rendering component: [MarkupContainer [Component id = 
fieldValue]]
org.apache.wicket.WicketRuntimeException: Exception in rendering 
component: [MarkupContainer [Component id = fieldValue]]
    at org.apache.wicket.Component.renderComponent(Component.java:2658)
    at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1512)
    at org.apache.wicket.Component.render(Component.java:2450)
    at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1414)
    at 
org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:15
77)
    at 
org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1501)
    at org.apache.wicket.Component.renderComponent(Component.java:2619)
    at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1512)
    at org.apache.wicket.Component.render(Component.java:2450)
    at 
org.apache.wicket.markup.html.list.ListView.renderItem(ListView.java:638)
    at 
org.apache.wicket.markup.html.list.ListView.renderChild(ListView.java:626)
    at 
org.apache.wicket.markup.repeater.AbstractRepeater.onRender(AbstractRepeater.jav
a:103)
    at org.apache.wicket.Component.render(Component.java:2450)
    at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1414)
    at 
org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:15
77)
    at 
org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1501)
    at org.apache.wicket.Component.renderComponent(Component.java:2619)
    at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1512)
    at org.apache.wicket.Component.render(Component.java:2450)
    at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1414)
    at 
org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:15
77)
    at 
org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1501)
    at org.apache.wicket.Component.renderComponent(Component.java:2619)
    at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1512)
    at org.apache.wicket.Component.render(Component.java:2450)
    at org.apache.wicket.Component.renderComponent(Component.java:2560)
    at 
org.apache.wicket.ajax.AjaxRequestTarget.respondComponent(AjaxRequestTarget.java
:828)
    at 
org.apache.wicket.ajax.AjaxRequestTarget.respondComponents(AjaxRequestTarget.jav
a:681)
    at 
org.apache.wicket.ajax.AjaxRequestTarget.respond(AjaxRequestTarget.java:591)
    at 
org.apache.wicket.request.AbstractRequestCycleProcessor.respond(AbstractRequestC
ycleProcessor.java:105)
    at 
org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1258)
    at org.apache.wicket.RequestCycle.step(RequestCycle.java:1329)
    at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1428)
    at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
    at 
org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:479)
    at 
org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:312)
    at 
weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:56)
    at 
weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAp
pServletContext.java:3588)
    at 
weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.ja
va:321)
    at 
weblogic.security.service.SecurityManager.runAs(SecurityManager.java:121)
    at 
weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletConte
xt.java:2200)
    at 
weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java
:2106)
    at 
weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1428)
    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:201)
    at weblogic.work.ExecuteThread.run(ExecuteThread.java:173)
Caused by: net.ontopia.persistence.proxy.TransactionNotActiveException: 
Transaction is not active.
    at 
net.ontopia.persistence.proxy.AbstractTransaction._getObject(AbstractTransaction
.java:235)
    at 
net.ontopia.persistence.proxy.AbstractRWPersistent.isLoaded(AbstractRWPersistent
.java:342)
    at 
net.ontopia.persistence.proxy.AbstractRWPersistent.loadCollectionField(AbstractR
WPersistent.java:118)
    at 
net.ontopia.topicmaps.impl.rdbms.Topic.getSubjectIdentifiers(Topic.java:161)
    at ontopoly.model.FieldsView.isDefaultView(FieldsView.java:61)
    at ontopoly.components.TopicLink.getPageParameters(TopicLink.java:57)
    at 
ontopoly.components.AbstractBookmarkablePageLink.getURL(AbstractBookmarkablePage
Link.java:216)
    at org.apache.wicket.markup.html.link.Link.onComponentTag(Link.java:408)
    at ontopoly.components.TopicLink.onComponentTag(TopicLink.java:66)
    at org.apache.wicket.Component.renderComponent(Component.java:2590)
    at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1512)
    at org.apache.wicket.Component.render(Component.java:2450)
    at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1414)
    at 
org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:15
77)
    at 
org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:67
5)
    at 
org.apache.wicket.markup.html.panel.Panel.onComponentTagBody(Panel.java:114)
    at org.apache.wicket.Component.renderComponent(Component.java:2619)
    ... 44 more


```

Original issue reported on code.google.com by `oveg...@gmail.com` on 25 May 2010 at 11:50

**Comment by qsiebers** [comment] 2017-04-11 15:17
Duplicate of #265

**Closed by qsiebers** 2017-04-11 15:17 UTC
Labels: Component-RDBMS, Defect, GoogleCode, Priority-Medium
